// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO: Add your web API key',
    appId: 'TODO: Add your web app ID',
    messagingSenderId: 'TODO: Add your messaging sender ID',
    projectId: 'TODO: Add your project ID',
    authDomain: 'TODO: Add your auth domain',
    databaseURL: 'TODO: Add your database URL',
    storageBucket: 'TODO: Add your storage bucket',
    measurementId: 'TODO: Add your measurement ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO: Add your Android API key',
    appId: 'TODO: Add your Android app ID',
    messagingSenderId: 'TODO: Add your messaging sender ID',
    projectId: 'TODO: Add your project ID',
    databaseURL: 'TODO: Add your database URL',
    storageBucket: 'TODO: Add your storage bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO: Add your iOS API key',
    appId: 'TODO: Add your iOS app ID',
    messagingSenderId: 'TODO: Add your messaging sender ID',
    projectId: 'TODO: Add your project ID',
    databaseURL: 'TODO: Add your database URL',
    storageBucket: 'TODO: Add your storage bucket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO: Add your macOS API key',
    appId: 'TODO: Add your macOS app ID',
    messagingSenderId: 'TODO: Add your messaging sender ID',
    projectId: 'TODO: Add your project ID',
    databaseURL: 'TODO: Add your database URL',
    storageBucket: 'TODO: Add your storage bucket',
  );
}
